### ISSUE TITLE
Do not enforce check of GITHUB_EVENT_NAME

### ISSUE THREAD

**Issue by mkungla** [actions-automation/organization-labels#3]
https://github.com/actions-automation/manage-your-labels/blob/08ca6a139b807f638d2f40826a805321d5a4187d/src/mirror-labels#L66-L67

GitHub workflow should handle when it's executed. 

e.g use case which currently fails silently because of `sys.exit(0)`

```
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/manage-labels.yml'
      - 'manage-your-labels.yml'
```
